import os
import io
import logging
import requests
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF

logger = logging.getLogger(__name__)

# Yieldera brand colors (matching weather report)
YIELDERA_DARK_TEAL = colors.Color(1/255, 40/255, 47/255)  # RGB(1, 40, 47)
YIELDERA_PRIMARY = colors.Color(182/255, 191/255, 0/255)  # RGB(182, 191, 0)

def download_logo():
    """Download Yieldera logo from URL"""
    try:
        logo_url = "https://yieldera.co.zw/assets/img/logo.svg"
        response = requests.get(logo_url, timeout=5)
        if response.status_code == 200:
            logo_buffer = io.BytesIO(response.content)
            return svg2rlg(logo_buffer)
        return None
    except Exception as e:
        logger.warning(f"Could not download logo: {e}")
        return None

def add_header_footer(canvas_obj, doc, report_date):
    """Add consistent header and footer to all pages"""
    canvas_obj.saveState()
    
    # Header with dark teal background
    canvas_obj.setFillColor(YIELDERA_DARK_TEAL)
    canvas_obj.rect(0, A4[1] - 50, A4[0], 50, fill=1, stroke=0)
    
    # Try to add logo
    try:
        logo = download_logo()
        if logo:
            # Scale logo to fit
            logo.width = 80
            logo.height = 25
            renderPDF.draw(logo, canvas_obj, 30, A4[1] - 40)
        else:
            # Fallback to text
            canvas_obj.setFillColor(colors.white)
            canvas_obj.setFont('Helvetica-Bold', 14)
            canvas_obj.drawString(30, A4[1] - 30, "YIELDERA")
    except:
        # Fallback to text if logo fails
        canvas_obj.setFillColor(colors.white)
        canvas_obj.setFont('Helvetica-Bold', 14)
        canvas_obj.drawString(30, A4[1] - 30, "YIELDERA")
    
    # Report title in center
    canvas_obj.setFillColor(colors.white)
    canvas_obj.setFont('Helvetica-Bold', 16)
    canvas_obj.drawCentredString(A4[0]/2, A4[1] - 30, "Agricultural Intelligence Report")
    
    # Date on right
    canvas_obj.setFont('Helvetica', 9)
    canvas_obj.drawRightString(A4[0] - 30, A4[1] - 30, report_date)
    
    # Footer
    canvas_obj.setFillColor(YIELDERA_DARK_TEAL)
    canvas_obj.rect(0, 0, A4[0], 30, fill=1, stroke=0)
    
    canvas_obj.setFillColor(colors.white)
    canvas_obj.setFont('Helvetica', 8)
    canvas_obj.drawCentredString(A4[0]/2, 15, f"Generated by Yieldera | {report_date}")
    
    # Page number
    page_num = canvas_obj.getPageNumber()
    canvas_obj.drawRightString(A4[0] - 30, 15, f"Page {page_num}")
    
    canvas_obj.restoreState()

def generate_pdf_report(report_data):
    """
    Generate professional PDF report matching weather report design.
    Returns a BytesIO object containing the PDF.
    """
    try:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=50,
            leftMargin=50,
            topMargin=70,  # Space for header
            bottomMargin=50  # Space for footer
        )

        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=styles['Heading2'],
            fontSize=13,
            textColor=YIELDERA_DARK_TEAL,
            spaceAfter=8,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))
        styles.add(ParagraphStyle(
            name='SubHeader',
            parent=styles['Heading3'],
            fontSize=11,
            textColor=colors.HexColor('#01282F'),
            spaceAfter=6,
            spaceBefore=8,
            fontName='Helvetica-Bold'
        ))
        styles.add(ParagraphStyle(
            name='VerdictHealthy',
            fontSize=12,
            textColor=colors.green,
            fontName='Helvetica-Bold'
        ))
        styles.add(ParagraphStyle(
            name='VerdictStress',
            fontSize=12,
            textColor=colors.orange,
            fontName='Helvetica-Bold'
        ))
        styles.add(ParagraphStyle(
            name='VerdictRisk',
            fontSize=12,
            textColor=colors.red,
            fontName='Helvetica-Bold'
        ))
        styles.add(ParagraphStyle(
            name='VerdictHarvested',
            fontSize=12,
            textColor=colors.grey,
            fontName='Helvetica-Bold'
        ))
        styles.add(ParagraphStyle(
            name='ReportBodyText',
            parent=styles['Normal'],
            fontSize=10,
            alignment=TA_JUSTIFY,
            spaceAfter=6
        ))
        styles.add(ParagraphStyle(
            name='MetadataBox',
            fontSize=9,
            textColor=YIELDERA_DARK_TEAL,
            leftIndent=10,
            spaceAfter=3
        ))

        story = []

        # Extract data
        field_info = report_data.get("database_field_info", {})
        growth_stage = report_data.get("growth_stage", {})
        exec_verdict = report_data.get("executive_verdict", "Pending")
        exec_summary = report_data.get("executive_summary", {})
        observation_meta = report_data.get("observation_metadata", {})
        
        # === OBSERVATION METADATA BOX (Matching weather report style) ===
        story.append(Paragraph("Satellite Observation Metadata", styles['SubHeader']))
        
        obs_date = observation_meta.get("satellite_observation_date", "N/A")
        date_range = f"{observation_meta.get('date_range_start', 'N/A')} to {observation_meta.get('date_range_end', 'N/A')}"
        data_source = observation_meta.get("data_source", "Sentinel-2 L2A")
        
        story.append(Paragraph(f"<b>Satellite Observation Date:</b> {obs_date}", styles['MetadataBox']))
        story.append(Paragraph(f"<b>Date Range Analyzed:</b> {date_range}", styles['MetadataBox']))
        story.append(Paragraph(f"<b>Data Source:</b> {data_source}", styles['MetadataBox']))
        story.append(Spacer(1, 15))

        # === FIELD DETAILS TABLE (Matching weather report style) ===
        story.append(Paragraph("Field Details", styles['SectionHeader']))
        
        field_details_data = [
            ["Field Name:", field_info.get("field_name", "N/A")],
            ["Crop Type:", field_info.get("crop", "N/A")],
            ["Area:", f"{field_info.get('area', 'N/A')} ha"],
            ["Planting Date:", field_info.get("planting_date", "N/A")],
            ["Irrigation:", field_info.get("irrigation", "N/A")],
            ["Location:", "Zimbabwe"]
        ]
        
        field_table = Table(field_details_data, colWidths=[2*inch, 4*inch])
        field_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.whitesmoke),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.white),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(field_table)
        story.append(Spacer(1, 15))

        # === CURRENT STATUS ===
        story.append(Paragraph("Current Status", styles['SectionHeader']))
        
        is_harvested = growth_stage.get('is_harvested', False)
        stage_display = growth_stage.get('stage', 'Unknown').title()
        if is_harvested:
            stage_display = "Harvested"
        
        # Fix for text cutoff: Wrap description in Paragraph
        description_text = growth_stage.get('stage_description', 'N/A')
        description_paragraph = Paragraph(description_text, styles['ReportBodyText'])

        status_data = [
            ["Growth Stage:", stage_display],
            ["Description:", description_paragraph],
            ["Days Since Planting:", str(growth_stage.get('days_since_planting', 'N/A'))]
        ]
        
        if not is_harvested and growth_stage.get('days_to_harvest'):
            status_data.append(["Days to Harvest:", f"~{growth_stage.get('days_to_harvest', 'N/A')}"])
        
        status_table = Table(status_data, colWidths=[2*inch, 4*inch])
        status_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.white),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'), # Align top for wrapped text
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(status_table)
        story.append(Spacer(1, 15))

        # === EXECUTIVE VERDICT ===
        story.append(Paragraph("Executive Verdict", styles['SectionHeader']))
        
        verdict_style = styles['Normal']
        if exec_verdict == "Healthy":
            verdict_style = styles['VerdictHealthy']
        elif exec_verdict in ["Moderate Stress", "High Risk"]:
            verdict_style = styles['VerdictStress'] if exec_verdict == "Moderate Stress" else styles['VerdictRisk']
        elif exec_verdict == "Harvested":
            verdict_style = styles['VerdictHarvested']
        
        story.append(Paragraph(f"<b>Status:</b> {exec_verdict}", verdict_style))
        story.append(Spacer(1, 6))
        
        verdict_data = [
            ["Crop Status:", exec_summary.get('crop_status', 'N/A')],
            ["Field Condition:", exec_summary.get('field_condition', 'N/A')],
            ["Management Priority:", exec_summary.get('management_priority', 'N/A')]
        ]
        
        verdict_table = Table(verdict_data, colWidths=[2*inch, 4*inch])
        verdict_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.beige),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.white),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(verdict_table)
        story.append(Spacer(1, 8))
        story.append(Paragraph(exec_summary.get("one_line_summary", "Analysis pending..."), styles['ReportBodyText']))
        
        # === FINAL FIELD VERDICT (Signature Closing Statement) ===
        final_verdict = report_data.get("final_field_verdict", "")
        if final_verdict:
            story.append(Spacer(1, 10))
            # Create a distinct box or style for the final verdict
            story.append(Paragraph(f"<b>FINAL VERDICT:</b> {final_verdict}", styles['ReportBodyText']))
        
        story.append(PageBreak())

        # === PAGE 2: ANALYSIS ===
        cross_synthesis = report_data.get("cross_index_synthesis", "")
        physiological = report_data.get("physiological_narrative", "")
        index_interp = report_data.get("index_interpretation", {})
        
        if cross_synthesis and cross_synthesis != "Analysis pending...":
            story.append(Paragraph("Cross-Index Synthesis", styles['SectionHeader']))
            story.append(Paragraph(cross_synthesis, styles['ReportBodyText']))
            story.append(Spacer(1, 12))

        if physiological and physiological != "Analysis pending...":
            story.append(Paragraph("Physiological Narrative", styles['SectionHeader']))
            story.append(Paragraph(physiological, styles['ReportBodyText']))
            story.append(Spacer(1, 12))

        # === VEGETATION INDICES SUMMARY TABLE ===
        story.append(Paragraph("Vegetation Indices Summary", styles['SectionHeader']))
        
        # Static descriptions
        index_descriptions = {
            "NDVI": "Measures crop vigor & biomass",
            "EVI": "Enhanced vigor (high biomass)",
            "SAVI": "Soil-adjusted vigor",
            "NDMI": "Vegetation moisture content",
            "NDWI": "Leaf water content"
        }
        
        indices_data = report_data.get("vegetation_indices", {})
        
        # Prepare table data
        summary_data = [["Index", "What it is", "Value", "Interpretation"]]
        
        for idx in ["NDVI", "EVI", "SAVI", "NDMI", "NDWI"]:
            idx_lower = idx.lower()
            
            # Get value - handle both direct float and dictionary (just in case)
            val_data = indices_data.get(idx_lower, "N/A")
            if isinstance(val_data, dict):
                val = val_data.get("current", "N/A")
            else:
                val = val_data

            if isinstance(val, (float, int)):
                val_str = f"{val:.2f}"
            else:
                val_str = str(val)
                
            # Get interpretation
            interp = index_interp.get(idx_lower, {}).get("interpretation", "Pending...")
            # Truncate if too long for table
            if len(interp) > 100:
                interp = interp[:97] + "..."
                
            summary_data.append([
                idx,
                index_descriptions.get(idx, ""),
                val_str,
                interp
            ])
            
        # Create table
        summary_table = Table(summary_data, colWidths=[0.8*inch, 1.5*inch, 0.8*inch, 3.5*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), YIELDERA_DARK_TEAL),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('TOPPADDING', (0, 0), (-1, 0), 8),
            
            ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
            ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 1, colors.white),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 15))

        story.append(Paragraph("Index-by-Index Interpretation", styles['SectionHeader']))
        
        for idx_name in ["ndvi", "evi", "savi", "ndmi", "ndwi"]:
            idx_data = index_interp.get(idx_name, {})
            if idx_data:
                idx_upper = idx_name.upper()
                story.append(Paragraph(f"<b>{idx_upper}:</b>", styles['SubHeader']))
                story.append(Paragraph(idx_data.get("interpretation", "N/A"), styles['ReportBodyText']))
                
                cause_effect = idx_data.get("cause_effect", "")
                if cause_effect:
                    story.append(Paragraph(f"<i>Why & What:</i> {cause_effect}", styles['Normal']))
                story.append(Spacer(1, 8))
        
        story.append(PageBreak())

        # === PAGE 3: TRENDS & GUIDANCE ===
        temporal = report_data.get("temporal_trend", {})
        confidence = report_data.get("confidence_assessment", {})
        farmer = report_data.get("farmer_guidance", {})
        
        story.append(Paragraph("Temporal Trend", styles['SectionHeader']))
        story.append(Paragraph(f"<b>Direction:</b> {temporal.get('direction', 'Unknown')}", styles['Normal']))
        story.append(Paragraph(temporal.get("statement", "N/A"), styles['ReportBodyText']))
        story.append(Spacer(1, 12))

        story.append(Paragraph("Confidence Assessment", styles['SectionHeader']))
        conf_score = confidence.get("score", 0.0)
        story.append(Paragraph(f"<b>Confidence Score:</b> {conf_score:.2f}", styles['Normal']))
        story.append(Paragraph(confidence.get("explanation", "N/A"), styles['ReportBodyText']))
        story.append(Spacer(1, 12))

        story.append(Paragraph("Farmer Guidance", styles['SectionHeader']))
        
        story.append(Paragraph("<b>Immediate Actions (0-7 Days):</b>", styles['SubHeader']))
        for action in farmer.get("immediate_actions_0_7_days", []):
            story.append(Paragraph(f"• {action}", styles['Normal']))
        story.append(Spacer(1, 6))

        story.append(Paragraph("<b>Field Checks:</b>", styles['SubHeader']))
        for check in farmer.get("field_checks", []):
            story.append(Paragraph(f"• {check}", styles['Normal']))
        story.append(Spacer(1, 6))

        harvest_guidance = farmer.get("harvest_or_next_season", "")
        if harvest_guidance and harvest_guidance != "Pending...":
            story.append(Paragraph("<b>Harvest / Next Season:</b>", styles['SubHeader']))
            story.append(Paragraph(harvest_guidance, styles['ReportBodyText']))
        
        story.append(PageBreak())

        # === PAGE 4: PROFESSIONAL ANALYSIS ===
        tech_notes = report_data.get("professional_technical_notes", {})
        agronomist = report_data.get("agronomist_notes", {})
        historical = report_data.get("historical_context", {})
        
        story.append(Paragraph("Professional Technical Notes", styles['SectionHeader']))
        
        for key, label in [
            ("canopy_structure", "Canopy Structure"),
            ("biomass_distribution", "Biomass Distribution"),
            ("moisture_stress_interaction", "Moisture-Stress Interaction"),
            ("senescence_quality", "Senescence Quality"),
            ("spatial_heterogeneity", "Spatial Heterogeneity")
        ]:
            value = tech_notes.get(key, "")
            if value and value != "Pending...":
                story.append(Paragraph(f"<b>{label}:</b> {value}", styles['ReportBodyText']))
        
        story.append(Spacer(1, 12))

        story.append(Paragraph("Agronomist Notes", styles['SectionHeader']))
        
        cause_effect = agronomist.get("cause_and_effect", "")
        if cause_effect and cause_effect != "Pending analysis...":
            story.append(Paragraph("<b>Cause & Effect Analysis:</b>", styles['SubHeader']))
            story.append(Paragraph(cause_effect, styles['ReportBodyText']))
            story.append(Spacer(1, 8))
        
        story.append(Paragraph(f"<b>Technical Summary:</b> {agronomist.get('technical_summary', 'N/A')}", styles['ReportBodyText']))
        story.append(Paragraph(f"<b>Yield Implications:</b> {agronomist.get('yield_implications', 'N/A')}", styles['ReportBodyText']))
        story.append(Spacer(1, 8))
        
        risk_factors = agronomist.get("risk_factors", [])
        if risk_factors:
            story.append(Paragraph("<b>Risk Factors:</b>", styles['SubHeader']))
            for factor in risk_factors:
                story.append(Paragraph(f"• {factor}", styles['Normal']))
        
        story.append(Spacer(1, 12))

        story.append(Paragraph("Historical Context", styles['SectionHeader']))
        story.append(Paragraph(f"<b>Comparison Period:</b> {historical.get('comparison_period', 'N/A')}", styles['Normal']))
        story.append(Paragraph(f"<b>Seasonal Trend:</b> {historical.get('seasonal_trend', 'N/A')}", styles['Normal']))
        story.append(Paragraph(f"<b>Trend Description:</b> {historical.get('trend_description', 'N/A')}", styles['ReportBodyText']))

        # Build PDF with header/footer
        report_date = observation_meta.get("satellite_observation_date", report_data.get("report_date", "N/A"))
        doc.build(story, onFirstPage=lambda c, d: add_header_footer(c, d, report_date),
                  onLaterPages=lambda c, d: add_header_footer(c, d, report_date))
        
        buffer.seek(0)
        return buffer

    except Exception as e:
        logger.error(f"Error generating PDF: {e}")
        import traceback
        logger.error(traceback.format_exc())
        return None
